### ISSUE TITLE
Alexa Support

### ISSUE THREAD

**Issue by ricokahler** [timleland/rfoutlet#3]
Hi there, I love the project so far but it seems to be missing something. I've read in your blog that you got rfoutlet to work with both siri and google home however, I don't have an iPhone or a google home 😢 .

Long story short, I've gone down the rabbit hole of rewriting rfoutlet with alexa support. It involves:
* creating a web service on the raspberry pi and
* exposing all of its endpoints globally for alexa skills kit to call it then finally
* securing the endpoints so anyone can't turn on your lights

It's quite a rabbit hole, but I'd be willing to help get alexa support in this project.

I regret not starting my project out as a fork but [here it is](https://github.com/ricokahler/alexa-rfoutlet).

**Comment by timleland** [comment]
Thanks for sharing. I'll take a look at how you got it to work. I plan on writing a post for the echo. 

How did you go about securing your raspberry pi? I'm a little concerned about exposing my pi to the internet. If possible, I would like to have Alexa [talk directly](https://www.reddit.com/r/amazonecho/comments/4d9vdc/can_i_use_echo_to_call_a_rest_api/) to the raspberry pi on my network.

Also using the same method for the [Google Home](https://timleland.com/use-google-home-to-control-wireless-power-outlets/) should work for the echo. It's not perfect but it works.

**Comment by ricokahler** [comment]
I secured my raspberry pi by using Auth0 since I'm no expert in OAuth2. The access token Alexa receives is not a ful JWT token so you'll need to do some special steps to get authentication working correctly. [This blog post](http://eugeniopace.org/alexa/webtask/auth0/2016/11/19/Alexa-Auth0-II.html#comment-3026995321) and [this thread](https://auth0.com/forum/t/using-auth0-for-amazon-alexa-account-linking/3911/8) helped a lot. 

Alexa does the voice processing in the cloud so there's no data to work with locally. [This](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/overviews/understanding-the-smart-home-skill-api) explains the architecture well. It probably would've been easier if alexa didn't talk to my pi directly and I had used some sort of bridge to talk to the pi.

Putting it together involves:
* creating a smart home skill (part of alexa skills kit) on amazon developer
* creating a lambda function on AWS that will call your public API on the pi (AWS is separate from amazon developer)
* creating a Auth0 client and API to handle authentication following that blog post above

Honestly I never thought of using IFTTT and it gets the job done with a lot less work 😓. It's clever.

**Comment by timleland** [comment]
I just posted my tutorial for using the Echo to control the outlets https://timleland.com/use-amazon-echo-to-control-wireless-power-outlets/. Check it out and let me know what you think. Let me know if you find any issues. I found this method to be pretty straightforward.

**Comment by ricokahler** [comment]
LGTM, assuming you've tested it, I think you've done it!

**Comment by timleland** [comment]
Thanks!
